run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 2

  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "不允许使用 logrus"
          - pkg: "github.com/pkg/errors"
            desc: "使用标准库 errors 或 fmt.Errorf"

  misspell:
    locale: US

  lll:
    line-length: 140

  goimports:
    local-prefixes: casbinx

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  funlen:
    lines: 100
    statements: 50

  gosec:
    excludes:
      - G401 # MD5 或 SHA1
      - G501 # MD5 hash
      - G502 # SHA1 hash

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
        - dupl

    - path: examples/
      linters:
        - gomnd
        - goconst

    - path: tests/
      linters:
        - gomnd
        - funlen
        - goconst
        - dupl

    # 排除一些无关紧要的问题
    - text: "weak cryptographic primitive"
      linters:
        - gosec

  exclude-use-default: false
  exclude:
    # errcheck: 忽略某些常见的错误检查
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

    # govet: 忽略shadow检查中的常见模式
    - "shadow: declaration of \"err\" shadows declaration at"

    # staticcheck: 忽略一些不重要的检查
    - "SA9003: empty branch"

  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
        - goconst
        - gomnd
      severity: warning

    - linters:
        - funlen
        - lll
      severity: info